### ISSUE TITLE
Agregar JWT a todas las rutas del server.

### ISSUE THREAD

**Issue by gerlis18** [gerlis18/NodeAPI#1]
Se necesita agregar seguridad a las rutas del servidor.

Se puede hacer con JWT u otro que consideren pertinente.

Aclaro: Todas las rutas deben estar protegidas, así que es mejor dejarlo como un **Middleware** para que filtre antes de llegar a cualquier ruta.

**Comment by PranjalSrivastava092** [comment]
He abierto un PR para este problema. Espero que satisfaga su demanda.

**Comment by gerlis18** [comment]
Solucionado por el pull request #2
