### ISSUE TITLE
Unit test with any library / Pruebas unitarias con cualquier librería

### ISSUE THREAD

**Issue by gerlis18** [gerlis18/NodeAPI#3]
**Unit test with Jest o Mocha / Pruebas unitarias con Jest o Mocha**

Crear ejemplo de pruebas unitarias con una de las dos librerías mencionadas
aplicado al API creado actualmente que es sobre **Animales / Animals**

**Tener en cuenta**
Al hacer el pull request se debe hacer sobre la rama de develop
Por favor leer la [Guía de de contribución](https://github.com/gerlis18/NodeAPI/blob/develop/CONTRIBUTING.md)

Tambien se puede tomar alguno de los pasos que estan en [Steps / Pasos](https://github.com/gerlis18/NodeAPI/tree/develop#pasos-a-seguir) y solucionarlos.

**Comment by to-var** [comment]
I can help you with this one

**Comment by gerlis18** [comment]
Thanks man :+1:

**Comment by to-var** [comment]
Apologies I can't work on this one for now. Please let somebody else to help 👍

**Comment by gerlis18** [comment]
Solved by #10.
Thanks men 👍
